# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bc35d164b1507d5e7b59b3a3a59e47bd0d8936bce0abdb674a744fac996cb6cad2791b992647b6f7f6baf713600e1ea141b5eecd447e812f32ecdeb96443f7c

test:
  secret_key_base: c0e61482a37302fc181e03d523f613706ace45d4c673f633ebafc9e1243fae3238226460f7f9f3e82b4eedbe58c8e65126d7f7a0ab91ea8cd84869a87a90d283

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
